### ISSUE TITLE
CUDA version of this lib

### ISSUE THREAD

**Issue by vlnguyen92** [markodjurovic/parallelLibSvm#1]
Hi,

I want to create a version of parallel SVM in CUDA (mostly for my own practicing). Is this a good idea?

**Comment by markodjurovic** [comment]
Hi,

I think it is very good idea. There are couple reason for that:
1. Most GPUs on servers used for data science are based on NVidia technology (tesla series cards).
2. Using CUDA features it is possible to gain even more speed improvement, than with this OpenCL 1.2 version.
3. It is very good for practice because of nature of problem. Algorithm is based on iterations, and it is not trivial to be implemented as parallel, so you got to deal with trade off what will be executing on device and what on the host.

Why I chose OpenCL instead of CUDA:
1. It is platform independent and some of servers, I was developing for, was based on FireGL and other AMD cards.
2. OpenCL 2.0 also provide possibilities for more speed up. (maybe one day it will be freely available OpenCL 2.0 version of this port)

I hope  that you will do that port, and that you will reach better results than I had.

With best wishes,
Marko Djurovic.
